src/Entity/Vehicle.php
<?php

namespace App\Entity;

use App\Repository\VehiculeRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VehiculeRepository::class)]
class Vehicule
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $marque;

    #[ORM\Column(type: 'string', length: 255)]
    private $model;

    #[ORM\Column(type: 'integer')]
    private $Year;

    #[ORM\Column(type: 'integer')]
    private $Km;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Carburant;

    #[ORM\Column(type: 'integer')]
    private $Puissance;

    #[ORM\ManyToOne(targetEntity: Type::class, inversedBy: 'vehicules')]
    #[ORM\JoinColumn(nullable: false)]
    private $type;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): self
    {
        $this->model = $model;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->Year;
    }

    public function setYear(int $Year): self
    {
        $this->Year = $Year;

        return $this;
    }

    public function getKm(): ?int
    {
        return $this->Km;
    }

    public function setKm(int $Km): self
    {
        $this->Km = $Km;

        return $this;
    }

    public function getCarburant(): ?string
    {
        return $this->Carburant;
    }

    public function setCarburant(?string $Carburant): self
    {
        $this->Carburant = $Carburant;

        return $this;
    }

    public function getPuissance(): ?int
    {
        return $this->Puissance;
    }

    public function setPuissance(int $Puissance): self
    {
        $this->Puissance = $Puissance;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): self
    {
        $this->type = $type;

        return $this;
    }
}

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}CarsUy Home{% endblock %}

{% block body %}
<h2>Latest Annonce</h2>
<div class="container">
    <div class="card">
      <div class="card-header">
        <img src="https://public.carjager.com/content/2020/03/21161940/Barchetta-01.jpg" alt="rover" />
      </div>
      <div class="card-body">
        <span class="tag tag-teal">{{type[1].typeofvehicle}}</span>
        <h4>
            <a href="{{ path('vehicle_detail', {'id': annonces[1].id}) }}">{{ annonces[1].title }}</a>
        </h4>
        <h5 class="price">{{annonces[1].price}}$</h1>
        <div class="card-desc">
          Year : {{vehicle[1].year}} <br>
          KM : {{vehicle[1].km}} <br>
          Carburant : {{vehicle[1].carburant}} <br>
          Puissance : {{vehicle[1].puissance}} cv <br>
        </div>
        <p><button>Add to Cart</button></p>
        <div class="user">
          <img src="https://w7.pngwing.com/pngs/81/570/png-transparent-profile-logo-computer-icons-user-user-blue-heroes-logo-thumbnail.png" alt="user" />
          <div class="user-info">
            <h7>{{user[1].UserName}}</h7>
          </div>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-header">
        <img src="https://autoline.lu/img/s/automobile-voiturette-de-golf-Marshell-DG-C2-2-8---1632920157871578490_big--21092915555753765800.jpg" alt="ballons" />
      </div>
      <div class="card-body">
        <span class="tag tag-teal">{{type[2].typeofvehicle}}</span>
        <h4>
            <a href="{{ path('vehicle_detail', {'id': annonces[2].id}) }}">{{ annonces[2].title }}</a>
        </h4>
        <h5 class="price">{{annonces[2].price}}$</h5>
        <div class="card-desc">
          Year : {{vehicle[2].year}} <br>
          KM : {{vehicle[2].km}} <br>
          Carburant : {{vehicle[2].carburant}} <br>
          Puissance : {{vehicle[2].puissance}} cv <br>
        </div>
        <p><button>Add to Cart</button></p>
        <div class="user">
          <img src="https://w7.pngwing.com/pngs/81/570/png-transparent-profile-logo-computer-icons-user-user-blue-heroes-logo-thumbnail.png" alt="user" />
          <div class="user-info">
            <h7>{{user[2].UserName}}</h7>
          </div>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-header">
        <img src="https://sf2.autoplus.fr/wp-content/uploads/autoplus/2021/06/84-maybach-57s-xenatec-coupe-1-750x410.jpg" alt="city" />
      </div>
      <div class="card-body">
        <span class="tag tag-pink">{{type[3].typeofvehicle}}</span>
        <h4>
            <a href="{{ path('vehicle_detail', {'id': annonces[3].id}) }}">{{ annonces[3].title }}</a>
        </h4>
        <h5 class="price">{{annonces[4].price}}$</h5>
        <div class="card-desc">
          Year : {{vehicle[3].year}} <br>
          KM : {{vehicle[3].km}} <br>
          Carburant : {{vehicle[3].carburant}} <br>
          Puissance : {{vehicle[3].puissance}} cv <br>
        </div>
        <p><button>Add to Cart</button></p>
        <div class="user">
          <img src="https://w7.pngwing.com/pngs/81/570/png-transparent-profile-logo-computer-icons-user-user-blue-heroes-logo-thumbnail.png" alt="user" />
          <div class="user-info">
            <h7>{{user[3].UserName}}</h7>
          </div>
        </div>
      </div>
    </div>
    <div class="card">
        <div class="card-header">
          <img src="https://jtgeek.com/wp-content/uploads/Luxgen5-front-650.jpg" alt="ballons" />
        </div>
        <div class="card-body">
          <span class="tag tag-purple">{{type[4].typeofvehicle}}</span>
          <h4>
            <a href="{{ path('vehicle_detail', {'id': annonces[4].id}) }}">{{ annonces[4].title }}</a>
          </h4>
          <h5 class="price">{{annonces[4].price}}$</h5>
          <div class="card-desc">
            Year : {{vehicle[4].year}} <br>
            KM : {{vehicle[4].km}} <br>
            Carburant : {{vehicle[4].carburant}} <br>
            Puissance : {{vehicle[4].puissance}} cv <br>
          </div>
          <p><button>Add to Cart</button></p>
          <div class="user">
            <img src="https://w7.pngwing.com/pngs/81/570/png-transparent-profile-logo-computer-icons-user-user-blue-heroes-logo-thumbnail.png" alt="user" />
            <div class="user-info">
              <h7>{{user[4].UserName}}</h7>
            </div>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-header">
          <img src="https://upload.wikimedia.org/wikipedia/commons/e/ea/Artega_GT.JPG" alt="ballons" />
        </div>
        <div class="card-body">
          <span class="tag tag-purple">{{type[5].typeofvehicle}}</span>
          <h4>
            <a href="{{ path('vehicle_detail', {'id': annonces[5].id}) }}">{{ annonces[5].title }}</a>
          </h4>
          <h5 class="price">{{annonces[5].price}}$</h5>
          <div class="card-desc">
            Year : {{vehicle[5].year}} <br>
            KM : {{vehicle[5].km}} <br>
            Carburant : {{vehicle[5].carburant}} <br>
            Puissance : {{vehicle[5].puissance}} cv <br>
          </div>
          <p><button>Add to Cart</button></p>
          <div class="user">
            <img src="https://w7.pngwing.com/pngs/81/570/png-transparent-profile-logo-computer-icons-user-user-blue-heroes-logo-thumbnail.png" alt="user" />
            <div class="user-info">
              <h7>{{user[5].Username}}</h7>
            </div>
          </div>
        </div>
      </div>
{% endblock %}